subscribers:

  camera_reading:
    topic: /camera/color/image_raw
    queue_size: 1

  depth_reading:
    topic: /camera/aligned_depth_to_color/image_raw
    queue_size: 1

  camera_info_reading:
    topic: /camera/color/camera_info
    

actions:

  camera_reading:
    name: /darknet_ros/check_for_objects

publishers:

  object_detector:
    topic: /darknet_ros/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /darknet_ros/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /darknet_ros/detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true
